name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2015)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2016)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2017)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2018)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2019)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2020)'

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 27727                          
          session: ${{ secrets.AOC_SESSION }}    
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)(?=.*2021)'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
