name: Build

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt install gcc-11 g++-11

    - name: Check out code
      uses: actions/checkout@v2.3.4

    - name: Build solutions
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_C_COMPILER=gcc-11 \
          -DCMAKE_CXX_COMPILER=g++-11 \
          ..
        make -j `nproc`
  macos:
    runs-on: macos-11
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4

    - name: Build solutions
      run: |
        mkdir build
        cd build
        cmake ..
        make -j `nproc`
