name: Build

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Install dependencies
      run: sudo apt install gcc-14 g++-14

    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'

    - name: Build solutions
      run: |
        cmake -S . -B build           \
          -DCMAKE_C_COMPILER=gcc-14   \
          -DCMAKE_CXX_COMPILER=g++-14
        cmake --build build --parallel

  macos:
    runs-on: macos-14
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        brew install gcc@14

    - name: Build solutions
      run: |
        cmake -S . -B build           \
          -DCMAKE_C_COMPILER=gcc-14   \
          -DCMAKE_CXX_COMPILER=g++-14
        cmake --build build --parallel
